### ISSUE TITLE
External IP not getting assigned to razeedash-lb service

### ISSUE THREAD

**Issue by developer1-kedar** [razee-io/Razee#109] opened 2020-06-04 18:49 UTC
**Describe the bug**
External IP not getting assigned to razeedash-lb service

**To Reproduce**
1. Follow step 2 in the link https://github.com/razee-io/Razee#installing-razeedash
2. Check services . External IP doesnt appear for razeedash-lb service

**Expected behavior**
External IP must appear for razeedash-lb service

**Screenshots**

**Kubernetes Version (kubectl version):**
lient Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:21:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6+IKS", GitCommit:"43e4e6c4d0732364dff505878c79211999c58e04", GitTreeState:"clean", BuildDate:"2020-05-20T20:29:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by dalehille** [comment] 2020-06-11 19:03
@developer1-kedar I was unable to reproduce your issue.  Here are the steps I took -- let me know if you did something differently.

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6+IKS", GitCommit:"43e4e6c4d0732364dff505878c79211999c58e04", GitTreeState:"clean", BuildDate:"2020-05-20T20:29:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

1. kubectl apply -f https://github.com/razee-io/Razee/releases/latest/download/razeedeploy.yaml

2. kubectl apply -f https://github.com/razee-io/Razee/releases/latest/download/razeedash-all-in-one.yaml

3. kubectl get service -n razee 
This shows an external-ip configured for razeedash-api-lb and razeedash-lb

**Comment by nathanleviere** [comment] 2020-08-19 17:44
closing as unable to reproduce. Please re-open if you still have issues.

**Closed by nathanleviere** 2020-08-19 17:44 UTC
Labels: bug
